package.json
- After merging next into main we were having trouble releasing in the latest dist-tag from npm because of the way we used the next dist-tag. It's meant for breaking change releases but we were using it for minor/patch. Let's try to get a clean state for 2.0
- Closes https://go.mparticle.com/work/UNI-290
BREAKING CHANGE: Starting fresh
=> chore: testing the release of 2.0 to go back to latest@main releases

src/components/navigation/GlobalNavigation/NavigationList.tsx
- global navigation menu items should never show the expand arrow icon
=> fix: hide expand icon in global navigation lists

src/components/navigation/GlobalNavigation/global-navigation.css
- While updating the Cortex to the latest version of the package, the build was failing. After some investigation, the issue was found with `@supports selector()` syntax that was used for the global nav styling. postcss-loader package in Cortex is outdated and probably does not know how to process this syntax. Updating packages in Cortex is complex and requires some time. As an easy fix, removing the query is more suitable, since it keeps the same logic in place and should resolve the compilation errors.
- Run global navigation stories. Confirm the scroll bar is using an updated style.
=> fix: remove "@supports selector()" from css

CHANGELOG.md, CONTRIBUTING.md, package-lock.json, package.json, release.config.cjs
- With the decision to use trunk based development, the `dev` branch doesn't make much sense anymore. This PR removes it and makes it so that it's possible to publish versions from feature branches.
We still need to investigate edge cases but we need this merged on `main` to do it.
- Running `npx semantic-release --dry-run`  is generating the following version: `1.10.1-release-process.1`.
- [Release works](https://github.com/mParticle/aquarium/actions/runs/8485401033/job/23250104110)
- [NPM version](https://www.npmjs.com/package/@mparticle/aquarium/v/1.11.0-release-process.1)
- Closes https://go.mparticle.com/work/UNI-264
=> feat: Allows publishing npm versions from feature branches

src/services/user-preferences/user-preferences.ts
- Current cookie creation used in the UPS doesn't set the `path` option which causes the cookie to use the last but one path from the URL. This causes problems when using the UPS in the platforms.
More information in [this Nancy PR](https://git.corp.mparticle.com/mParticle/mPServer/pull/28254)
- This was tested by fixing it in Nancy's codebase which still had the UPS code.
=> fix: fixes path to be / on UPS cookie creation options

src/components/general/Button/Button.stories.tsx, src/components/general/Button/Button.tsx, src/components/general/Button/button.css, src/utils/utils.css
Currently, we are adding an icon through the icon prop. While version 5.17 (we are currently in 5.13) introduces iconPosition this prop only allows switching the icon between the left and right sides, not centering it.
Since we are adding it though props and not in the children, we can't use a Flex container to make the button aligned, and we can't let the children handle the alignment either. Here is a code snippet from ant's implementation on the icon/children. The rest of the code you can find it [here](https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L261):
```
const genButtonContent = (iconComponent: React.ReactNode, kidsComponent: React.ReactNode) =>
iconPosition === 'start' ? (
<>
{iconComponent}
{kidsComponent}
</>
) : (
<>
{kidsComponent} …
```
=> fix: Align button content to the center

src/components/navigation/GlobalNavigation/GlobalNavigation.stories.tsx, src/components/navigation/GlobalNavigation/GlobalNavigationItems.d.ts, src/components/navigation/GlobalNavigation/HomeButton.tsx, src/components/navigation/MiniMap/MiniMap.tsx, src/components/navigation/MiniMap/miniMap.css
- {provide a thorough description of the changes}
=> feat: unnesting minimap styles

src/components/data-display/Table/Table.tsx, src/components/data-display/Tag/Tag.tsx, src/components/data-entry/QueryItem/Cascader.stories.tsx
- Adds generic template type for use in platforms 
- Closes https://go.mparticle.com/work/UI3DM-1245
=> chore: add generic typing to table component

src/components/navigation/GlobalNavigation/HomeButton.tsx
This PR ensures that the popover is closed when the user clicks on a link inside the svg
[Component live:](https://65aec861fa4adbf0708aebd0-tmzgajeyji.chromatic.com/?path=/story/aquarium-navigation-globalnavigation--mp )
- Closes https://go.mparticle.com/work/UNI-654
=> fix: hide minimap after user clicks on a button

src/components/data-entry/QueryItem/Text.tsx, src/components/data-entry/QueryItem/TextInput.tsx, src/components/general/Typography/Typography.tsx
- the typography component from the aquarium has `word-break: break-word;`, which causes the component to wrap (see screenshot)
this can be turned off by adding [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space): nowrap
=> chore: dont allow wrapping of query item text component

src/components/general/Typography/Text.stories.tsx, src/components/general/Typography/Typography.tsx
- [EAMES](https://www.figma.com/design/LffDbOUjeYqDMZ3djs9Cga/mParticle-Foundation-v1.0.1?node-id=3745-8164&m=dev) specifies a size for a `Text` component. 
- Tested in storybook, using a control. Default behaviour (`base`) is preserved so it's backwards compat.
=> feat: Add size prop to `Typography.Text` component

src/components/general/Button/Button.tsx, src/utils/utils.css
this fix solves the issue that when no text, the icon is not aligned
=> fix: button-alligned center

src/components/data-entry/QueryItem/ValueSelector.stories.tsx
Automated tests run with `npm run test-storybook` would fail consistently on the ValueSelector story, citing:
```
error: ReferenceError: Cannot access 'ValueSelector' before initialization
```
- Closes https://mparticle-eng.atlassian.net/browse/UNI-742
=> fix: lazy load ValueSelector to fix Storybook test runner

src/services/user-preferences/README.md
Adds README for UPS
N/A
- Closes https://go.mparticle.com/work/uni-120
=> feat: adds README for UPS

release.config.cjs
> No need to keep instructions in the final PR description
Fixes release workflow for branches that use '_', which is not valid under semantic versioning. 
2. PR title prefix should state semantic value for the change, usually `feat:`, `fix:` or `chore:`. [Source.](https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml)
3. PR branch prefix should state the same as the above with a `/`, usually `feat/`, `fix/` or `chore/`. [Source.](https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml)
- {provide a thorough description of the changes}
- Closes …
=> chore: replace '_' with '-' during release

src/components/navigation/GlobalNavigation/WorkspaceSelector/workspace-selector.css, src/components/navigation/GlobalNavigation/global-navigation.css
Adjusts the height of the Workspace Selector in nav to be 94px (matching vertical padding of other nav elements) and better positions the avatar/text. 
- Closes https://mparticle-eng.atlassian.net/browse/UNI-816
=> fix: workspace selector positioning

CHANGELOG.md, package-lock.json, package.json, src/components/navigation/GlobalNavigation/GlobalNavigation.stories.tsx, src/components/navigation/GlobalNavigation/GlobalNavigation.tsx, src/components/navigation/GlobalNavigation/GlobalNavigationItems.d.ts, src/components/navigation/MiniMap/MiniMap.tsx
- Found this problem while updating Aquarium's version in Predictions codebase. There's a brief moment where there's no `orgs` cause they are loaded afterwards and thus the UI was calling the signout onClick automatically.
- Closes https://go.mparticle.com/work/UNI-815
=> fix: signout onclick being triggered on render when there are no orgs

src/components/data-display/Empty/Empty.stories.tsx, src/components/data-display/Empty/Empty.tsx, src/components/data-display/Empty/empty.css
- This PR adds the possibility to make the image of the Empty component bigger through props 
=> fix: add width auto to be able to manage the wdith from the component

src/components/navigation/GlobalNavigation/WorkspaceSelector/WorkspaceSelectorContentItems.tsx
Some users have a long list of orgs/accounts/workspaces available, which was causing some slowness on this component, because it was rendering the whole list of items on every re-render.
This PR changes it to use virtualization, which means that it will render only the items visible to the user. 
- used the `mp-thousand-orgs` test in storybook to confirm performace improvments
- validated no side effects on other use-cases
- Closes https://go.mparticle.com/work/UNI-830
=> fix: improve workspace selector performace

CHANGELOG.md, package-lock.json, package.json, src/components/data-display/Tour/Tour.stories.tsx, src/components/navigation/GlobalNavigation/GlobalNavigation.stories.tsx, src/components/navigation/GlobalNavigation/GlobalNavigationItems.d.ts, src/components/navigation/GlobalNavigation/SuiteLogo.tsx
- Based on the user's request, we will move the nav switcher (minimap) to the top of the nav bar and open it on suite logo hover. To bring awareness to the change, we are adding a Tour component, to highlight the area of change. This PR contains the implementation of this component.
- Run the `MP With Nav Switcher Tour` story in GlobalNavigation. Clicking on the SuiteLogo to see the tour popup.
- Closes https://mparticle-eng.atlassian.net/browse/UNI-881
=> feat: update SuiteLogo in GlobalNav to render nav switcher Tour

src/components/navigation/GlobalNavigation/GlobalNavigation.stories.tsx, src/components/navigation/GlobalNavigation/GlobalNavigation.tsx, src/components/navigation/GlobalNavigation/HomeButton.tsx, src/components/navigation/GlobalNavigation/SuiteLogo.tsx, src/components/navigation/MiniMap/MiniMap.tsx, src/utils/utils.css
- Based on user feedback, it was decided to move the minimap to the top of the nav bar and open on suite logo hover. 
- Design spec: https://www.figma.com/design/Zua9XIORG5fXRnrs2FZkfJ/Overview-Map-post-GA-Improvements?node-id=5317-12165&m=dev
- **Important**: should only be merged after https://github.com/mParticle/aquarium/pull/367. 
- Run `Global Navigation` stories (mp or cortex) confirm minimap now opens on top nav logo hover.
- Run `Global Navigation: MP With Nav Switcher Tour` on Suite Logo hover you''ll get the minimap, on click the Tour popover.
- Closes https://mparticle-eng.atlassian.net/browse/UNI-880
=> feat: move minimap to suite logo

src/components/navigation/GlobalNavigation/global-navigation.css
- We used the wrong color token for an active link in the nav bar, and with the recent tokens update it looks a bit odd. Thie PR brings an update to use the right color token.
- Open global nav stories. Confirm that the active link is using the correct background-color (`var(--control-item-bg-active)`)
=> fix: update nav link active background color

CHANGELOG.md, package-lock.json, package.json, src/components/navigation/GlobalNavigation/SuiteSelector/suite-selector.css, src/components/navigation/GlobalNavigation/global-navigation.css
-Nesting css classes is not working properly in CDP production. This PR contains a fix to the nav logo and home logo in the global navigation to unnest the SVG and make them use proper styling in CDP production.
- Tested with feature branch release in CDP PR env, and confirmed it worked.
- Closes Part of: https://mparticle-eng.atlassian.net/browse/UNI-967
=> fix: unnest css

src/components/navigation/GlobalNavigation/SuiteSelector/SuiteSelectorContent.tsx
- Updating suite selector cards with horizontal gaps.
- Run global navigation stories. Confirm that the suite selector has a horizontal gap between links.
=> fix: add horizontal gap in suite selector

src/components/data-entry/DatePicker/DatePicker.stories.tsx
This PR adds an example to the DatePicker component with a custom tooltip for disabled years.
https://github.com/user-attachments/assets/e1198644-a03b-4775-9044-bb6340bd3f05
=> feat: add datepicker example

CONTRIBUTING.md, docs/Contributing/Testing in the platforms.mdx, package-lock.json, package.json
- This PR adds a `build`  command that fixes one of the issues with local linking in the platforms. We were not including the styles files in the dist/ folder when running `npx vite build` manually so platforms were missing it.
It also changes docs to reflect latest instructions.
- Closes https://go.mparticle.com/work/UNI-1076
- Closes https://go.mparticle.com/work/UNI-1085
=> chore: new docs regarding testing in the platforms

CHANGELOG.md, package-lock.json, package.json, vite.config.js
This PR changes the build for Aquarium to preserve the file structure for types and thus fixing the exported types that were not correct.
Tested this using the link process, now need to debug why semantic-release is failing to release a version for us to test in the platforms
- Closes https://go.mparticle.com/work/UNI-153
=> fix: exported types

docs/components/Data Display/Tooltip/Documentation.mdx, docs/components/Data Entry/Select/Documentation.mdx
- Tooltip and Select docs coming from #462
=> docs: tooltip and select docs

.storybook/manager.css, .storybook/manager.ts, .storybook/manager.tsx, .storybook/preview.tsx, src/components/navigation/Dropdown/Dropdown.stories.tsx
- Ability to assign Badge.Ribbon to component stories via tags based on [shilman/storybook-tag-badges](https://github.com/shilman/storybook-tag-badges). Not definitive where we are going to use this yet but design requested the ability to be able to do so.
- Also tried [@geometricpanda/storybook-addon-badges](https://storybook.js.org/addons/@geometricpanda/storybook-addon-badges) but couldn't make it work as expected.
- Closes https://go.mparticle.com/work/UNI-1073
=> docs: ability to assign badges to stories and dropdown as an example

src/components/data-entry/QueryItem/query-item.css
remove --mp-query-item-* variables, and prefer underlying tokens instead
- validate in storybook
- validated with design
- see [figma](https://www.figma.com/design/seyMatkWGt0FCRJv1vB6II/Eames-2.0---Custom-Components?node-id=1002-7716&node-type=text&m=dev) for underlying token mapping
- Closes https://go.mparticle.com/work/UI3DM-1539
=> feat: deprecate mp-query-item tokens

src/components/feedback/Modal/modal.css
This PR adds styles of the modal back to fix this issue:
with the fix:
I built aquarium locally and tested it in Nancy
=> fix: (styles) update font weight of modal

.storybook/preview.tsx, docs/components/Data Display/Badge/Documentation.mdx, src/components/data-display/Badge/Badge.stories.tsx, src/components/data-entry/DatePicker/DatePicker.stories.tsx
The goal of this PR is to make our `Documentation` pages be the first ones in the list so that when a user clicks in a Story it goes directly to them instead of an example story. Storybook 7 provides 2 ways of sorting stories: 1. providing a nested `options.storySort.order` array containing stories titles in sorted order or 2. providing an `options.storySort` function that acts as a standard sort function (receives 2 stories, returns 1, 0, -1). 
I went down the rabbit hole of implementing our own sorting function because I couldn't figure it out why our documentation pages were not being considered until I've stumbled upon `options.storySort.includeNames` option which defaults to `false`. Default here means actual story names ("Documentation") were not included for sorting and storybook …
=> docs: documentation pages now appear first when clicking a story

package-lock.json, package.json, src/components/index.ts, src/constants/ChartColors.ts, src/constants/ChartConfig.ts
- Add constants, in the form of chart configs, and shaded colors
- This logic is extracted from analytics, to ensure the same styles are applied across all highcharts
- Nancy pr
- Analytics pr
- linked locally in nancy, with corresponding story
- tested in analytics via dist in branch
- Closes https://go.mparticle.com/work/UI3DM-1967
=> feat: highcharts configs

src/components/general/Typography/Text.stories.tsx, src/components/general/Typography/Typography.tsx
- @leobel discovered an issue with passing passing `size`, `color`  and `style` props to typography components, the style is overriding the size and color. This PR brings a fix to the typography components style prop passing.
- Run Text: Example Props story
=> refactor: update typography style prop passing
